name: build-installer

on:
  push:
  workflow_dispatch:

jobs:
  build-installer:
    runs-on: windows-latest
    permissions:
      packages: read
    env:
      NuGetPackageSourceCredentials_xcpng: Username=stormi;Password=${{secrets.GITHUB_TOKEN}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Add MSBuild
        uses: microsoft/setup-msbuild@v2
      - name: Restore
        run: msbuild . -t:Restore -p:Configuration=Release -p:Platform=x64
      - name: Build
        run: msbuild . -t:Build -p:Configuration=Release -p:Platform=x64
