name: build-installer

on:
  push:
  workflow_dispatch:

jobs:
  build-installer:
    runs-on: windows-latest
    permissions:
      packages: read
    env:
      NuGetPackageSourceCredentials_xcpng: Username=stormi;Password=${{secrets.GITHUB_TOKEN}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Add MSBuild
        uses: microsoft/setup-msbuild@v2
      - name: Build
        run: .\build.ps1
